#!/usr/bin/env bash
#
# ReconForge — one-shot installer for the API + worker + web UI stack.
#
# What this does, end to end:
#   1. Verifies the host has the prereqs (python3.11+, node 20+, git).
#   2. Creates apps/api/.venv, installs API + alembic + dev deps.
#   3. Runs `npm install` in apps/web.
#   4. Writes apps/api/.env from the template if it doesn't exist yet.
#   5. Initialises the SQLite schema (alembic upgrade head) for local dev.
#   6. Drops a permanent launcher at /usr/local/bin/reconforge so anywhere on
#      the system you can run `reconforge up`, `reconforge api`, `reconforge web`,
#      `reconforge worker`, `reconforge stop`, `reconforge logs`, `reconforge status`.
#
# Re-run is safe — every step is idempotent.
#
# Live recon tools (subfinder, nuclei, dalfox, ...) are *not* installed by this
# script; run `scripts/install-tools.sh` separately for that. Dry-run mode
# does not need any of them.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
API_DIR="${REPO_DIR}/apps/api"
WEB_DIR="${REPO_DIR}/apps/web"
VENV_DIR="${API_DIR}/.venv"
PYTHON_BIN="${PYTHON_BIN:-python3}"
LAUNCHER_PATH="${LAUNCHER_PATH:-/usr/local/bin/reconforge}"

log()  { printf '\033[1;36m[reconforge]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[reconforge]\033[0m %s\n' "$*" >&2; }
fail() { printf '\033[1;31m[reconforge]\033[0m %s\n' "$*" >&2; exit 1; }

ensure_python() {
  command -v "${PYTHON_BIN}" >/dev/null \
    || fail "Python (${PYTHON_BIN}) not found. Install Python 3.11+ first."
  local v
  v=$("${PYTHON_BIN}" -c 'import sys; print("%d.%d" % sys.version_info[:2])')
  case "${v}" in
    3.11|3.12|3.13|3.14) log "Python ${v} OK" ;;
    *) fail "Python 3.11+ required (found ${v})" ;;
  esac
}

ensure_node() {
  command -v node >/dev/null || fail "Node.js (>=20) not found. Install from https://nodejs.org first."
  command -v npm >/dev/null  || fail "npm not found. Install Node.js with npm."
  local major
  major=$(node -p 'process.versions.node.split(".")[0]')
  if (( major < 20 )); then
    warn "Node ${major}.x detected — Vite 8 wants Node >= 20. Build may fail."
  else
    log "Node $(node -v) OK"
  fi
}

bootstrap_api() {
  log "Bootstrapping Python venv at ${VENV_DIR}"
  if [[ ! -d "${VENV_DIR}" ]]; then
    "${PYTHON_BIN}" -m venv "${VENV_DIR}"
  fi
  # shellcheck disable=SC1091
  . "${VENV_DIR}/bin/activate"
  pip install --upgrade --quiet pip wheel
  log "Installing API package (editable)"
  pip install --quiet -e "${API_DIR}"
  log "Installing test deps (pytest)"
  pip install --quiet pytest pytest-asyncio anyio
  deactivate
}

bootstrap_web() {
  log "Installing web deps in ${WEB_DIR}"
  (cd "${WEB_DIR}" && npm install --silent)
}

write_env() {
  local env_path="${API_DIR}/.env"
  if [[ -f "${env_path}" ]]; then
    log ".env already exists — leaving alone"
    return
  fi
  log "Writing default .env to ${env_path}"
  cat > "${env_path}" <<'ENV'
# Local-dev defaults — safe to edit. Production should set these via secret manager.
APP_NAME=ReconForge
ENVIRONMENT=development
# Lab-mode default — live recon tools fire when a profile runs. Flip back
# to dry_run / false before exposing this to anything you don't fully control.
EXECUTION_MODE=live
ALLOW_LIVE_EXECUTION=true
RUNNER_MODE=in_process
DATABASE_URL=sqlite:///./reconforge.db
ARTIFACT_BACKEND=local
ARTIFACT_DIR=./artifacts
TOOL_REGISTRY_DIR=../../packages/tool-registry/tools
PROFILE_REGISTRY_DIR=../../packages/tool-registry/profiles
PLATFORM_CONFIG_PATH=../../packages/platform-config/sniper-inspired.yaml
GREP_PATTERNS_PATH=../../packages/patterns/sniper-grep-patterns.yaml
WORDLISTS_DIR=../../packages/wordlists
RECONFORGE_BOOTSTRAP_ADMIN_USERNAME=admin
RECONFORGE_BOOTSTRAP_ADMIN_PASSWORD=admin-passw0rd
CORS_ORIGINS=http://localhost:5173
# Set ANTHROPIC_API_KEY to enable the Claude advisor.
# ANTHROPIC_API_KEY=sk-ant-...
ENV
}

migrate() {
  log "Running alembic upgrade head"
  (cd "${API_DIR}" && "${VENV_DIR}/bin/alembic" upgrade head 2>/dev/null) \
    || warn "alembic upgrade failed — run \`reconforge migrate\` once you've fixed the cause."
}

write_launcher() {
  local target="${LAUNCHER_PATH}"
  log "Installing launcher at ${target}"
  local tmp
  tmp="$(mktemp)"
  cat > "${tmp}" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/install-stack.sh — do not edit by hand.
# Re-run scripts/install-stack.sh to regenerate.
exec "${REPO_DIR}/scripts/reconforge" "\$@"
EOF
  if [[ -w "$(dirname "${target}")" ]]; then
    install -m 0755 "${tmp}" "${target}"
  else
    sudo install -m 0755 "${tmp}" "${target}"
  fi
  rm -f "${tmp}"
  log "Launcher ready — try: reconforge --help"
}

main() {
  log "ReconForge stack installer — repo: ${REPO_DIR}"
  ensure_python
  ensure_node
  bootstrap_api
  bootstrap_web
  write_env
  migrate
  write_launcher
  cat <<MSG

  ✓ Stack installed.

  Next:
    reconforge up       # start API (8000) + web (5173) in foreground
    reconforge api      # API only
    reconforge web      # web only
    reconforge worker   # background worker
    reconforge test     # run pytest
    reconforge stop     # kill any reconforge-managed processes
    reconforge status   # show what's running
    reconforge logs     # tail logs

  For live tools (nuclei, subfinder, dalfox, ...) run:
    scripts/install-tools.sh

MSG
}

main "$@"
