"""advisor advice

Revision ID: 47cd5caea5c3
Revises: 739bcb570d56
Create Date: 2026-05-09 19:41:53.346518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '47cd5caea5c3'
down_revision: Union[str, Sequence[str], None] = '739bcb570d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advice',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('ref_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advice_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_advice_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_advice_ref_id'), ['ref_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_advice_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advice_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_advice_ref_id'))
        batch_op.drop_index(batch_op.f('ix_advice_kind'))
        batch_op.drop_index(batch_op.f('ix_advice_actor_id'))

    op.drop_table('advice')
    # ### end Alembic commands ###
