"""auth + audit

Revision ID: 739bcb570d56
Revises: f767e98c7690
Create Date: 2026-05-09 18:32:49.213132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '739bcb570d56'
down_revision: Union[str, Sequence[str], None] = 'f767e98c7690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditevent',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actor_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('target_kind', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('prev_signature', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('signature', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditevent_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditevent_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditevent_sequence'), ['sequence'], unique=True)
        batch_op.create_index(batch_op.f('ix_auditevent_signature'), ['signature'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditevent_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditevent_target_kind'), ['target_kind'], unique=False)

    op.create_table('user',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('viewer', 'operator', 'admin', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('apikey',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('token_sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apikey', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apikey_prefix'), ['prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_apikey_token_sha256'), ['token_sha256'], unique=True)
        batch_op.create_index(batch_op.f('ix_apikey_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apikey', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apikey_user_id'))
        batch_op.drop_index(batch_op.f('ix_apikey_token_sha256'))
        batch_op.drop_index(batch_op.f('ix_apikey_prefix'))

    op.drop_table('apikey')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_is_active'))

    op.drop_table('user')
    with op.batch_alter_table('auditevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditevent_target_kind'))
        batch_op.drop_index(batch_op.f('ix_auditevent_target_id'))
        batch_op.drop_index(batch_op.f('ix_auditevent_signature'))
        batch_op.drop_index(batch_op.f('ix_auditevent_sequence'))
        batch_op.drop_index(batch_op.f('ix_auditevent_actor_id'))
        batch_op.drop_index(batch_op.f('ix_auditevent_action'))

    op.drop_table('auditevent')
    # ### end Alembic commands ###
