"""loot items

Revision ID: 910e32683088
Revises: abfd3e65f469
Create Date: 2026-05-27 00:47:36.354620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '910e32683088'
down_revision: Union[str, Sequence[str], None] = 'abfd3e65f469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lootitem',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('finding_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('artifact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('value_preview', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_tool', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifact.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lootitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lootitem_artifact_id'), ['artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lootitem_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lootitem_host'), ['host'], unique=False)
        batch_op.create_index(batch_op.f('ix_lootitem_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_lootitem_label'), ['label'], unique=False)
        batch_op.create_index(batch_op.f('ix_lootitem_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lootitem_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_lootitem_source_tool'), ['source_tool'], unique=False)
        batch_op.create_index(batch_op.f('ix_lootitem_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lootitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lootitem_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_lootitem_source_tool'))
        batch_op.drop_index(batch_op.f('ix_lootitem_severity'))
        batch_op.drop_index(batch_op.f('ix_lootitem_run_id'))
        batch_op.drop_index(batch_op.f('ix_lootitem_label'))
        batch_op.drop_index(batch_op.f('ix_lootitem_kind'))
        batch_op.drop_index(batch_op.f('ix_lootitem_host'))
        batch_op.drop_index(batch_op.f('ix_lootitem_finding_id'))
        batch_op.drop_index(batch_op.f('ix_lootitem_artifact_id'))

    op.drop_table('lootitem')
    # ### end Alembic commands ###
