"""http exchanges

Revision ID: abfd3e65f469
Revises: 47cd5caea5c3
Create Date: 2026-05-09 19:52:05.119311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'abfd3e65f469'
down_revision: Union[str, Sequence[str], None] = '47cd5caea5c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('httpexchange',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=True),
    sa.Column('tool_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('request_body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_body_truncated', sa.Boolean(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('response_body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_body_truncated', sa.Boolean(), nullable=False),
    sa.Column('response_size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('httpexchange', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_httpexchange_host'), ['host'], unique=False)
        batch_op.create_index(batch_op.f('ix_httpexchange_method'), ['method'], unique=False)
        batch_op.create_index(batch_op.f('ix_httpexchange_response_status'), ['response_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_httpexchange_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_httpexchange_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_httpexchange_step_index'), ['step_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_httpexchange_tool_id'), ['tool_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_httpexchange_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('httpexchange', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_httpexchange_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_httpexchange_tool_id'))
        batch_op.drop_index(batch_op.f('ix_httpexchange_step_index'))
        batch_op.drop_index(batch_op.f('ix_httpexchange_started_at'))
        batch_op.drop_index(batch_op.f('ix_httpexchange_run_id'))
        batch_op.drop_index(batch_op.f('ix_httpexchange_response_status'))
        batch_op.drop_index(batch_op.f('ix_httpexchange_method'))
        batch_op.drop_index(batch_op.f('ix_httpexchange_host'))

    op.drop_table('httpexchange')
    # ### end Alembic commands ###
