"""workflows

Revision ID: d5d7a42ce9c6
Revises: 910e32683088
Create Date: 2026-05-28 16:15:41.769982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd5d7a42ce9c6'
down_revision: Union[str, Sequence[str], None] = '910e32683088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_name'))
        batch_op.drop_index(batch_op.f('ix_workflow_created_by'))

    op.drop_table('workflow')
    # ### end Alembic commands ###
