"""webhooks

Revision ID: d7570e0e6785
Revises: d5d7a42ce9c6
Create Date: 2026-05-29 21:59:37.227485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd7570e0e6785'
down_revision: Union[str, Sequence[str], None] = 'd5d7a42ce9c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.Integer(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_name'))
        batch_op.drop_index(batch_op.f('ix_webhook_is_active'))
        batch_op.drop_index(batch_op.f('ix_webhook_created_by'))

    op.drop_table('webhook')
    # ### end Alembic commands ###
