"""initial schema

Revision ID: f767e98c7690
Revises: 
Create Date: 2026-05-09 17:48:39.882296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f767e98c7690'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_name'), ['name'], unique=False)

    op.create_table('target',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('in_scope', sa.Boolean(), nullable=False),
    sa.Column('passive_allowed', sa.Boolean(), nullable=False),
    sa.Column('active_allowed', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('target', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_target_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_target_value'), ['value'], unique=False)
        batch_op.create_index(batch_op.f('ix_target_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('run',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', 'cancelled', name='runstatus'), nullable=False),
    sa.Column('risk', sa.Enum('passive', 'low_active', 'medium_active', 'high_active', name='risklevel'), nullable=False),
    sa.Column('requested_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_risk'), ['risk'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('artifact',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('storage_backend', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bucket', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('object_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_storage_backend'), ['storage_backend'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('asset',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_value'), ['value'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('runevent',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runevent_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_runevent_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runevent_sequence'), ['sequence'], unique=False)
        batch_op.create_index(batch_op.f('ix_runevent_type'), ['type'], unique=False)

    op.create_table('runstep',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'retrying', 'completed', 'failed', 'timed_out', 'cancelled', name='stepstatus'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('continue_on_error', sa.Boolean(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runstep', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runstep_index'), ['index'], unique=False)
        batch_op.create_index(batch_op.f('ix_runstep_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runstep_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_runstep_tool_id'), ['tool_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runstep_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('finding',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tool_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_finding_title'))
        batch_op.drop_index(batch_op.f('ix_finding_status'))
        batch_op.drop_index(batch_op.f('ix_finding_severity'))
        batch_op.drop_index(batch_op.f('ix_finding_run_id'))
        batch_op.drop_index(batch_op.f('ix_finding_category'))
        batch_op.drop_index(batch_op.f('ix_finding_asset_id'))

    op.drop_table('finding')
    with op.batch_alter_table('runstep', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runstep_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_runstep_tool_id'))
        batch_op.drop_index(batch_op.f('ix_runstep_status'))
        batch_op.drop_index(batch_op.f('ix_runstep_run_id'))
        batch_op.drop_index(batch_op.f('ix_runstep_index'))

    op.drop_table('runstep')
    with op.batch_alter_table('runevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runevent_type'))
        batch_op.drop_index(batch_op.f('ix_runevent_sequence'))
        batch_op.drop_index(batch_op.f('ix_runevent_run_id'))
        batch_op.drop_index(batch_op.f('ix_runevent_level'))

    op.drop_table('runevent')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_asset_value'))
        batch_op.drop_index(batch_op.f('ix_asset_type'))
        batch_op.drop_index(batch_op.f('ix_asset_source'))
        batch_op.drop_index(batch_op.f('ix_asset_run_id'))

    op.drop_table('asset')
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_artifact_type'))
        batch_op.drop_index(batch_op.f('ix_artifact_storage_backend'))
        batch_op.drop_index(batch_op.f('ix_artifact_run_id'))

    op.drop_table('artifact')
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_run_target_id'))
        batch_op.drop_index(batch_op.f('ix_run_status'))
        batch_op.drop_index(batch_op.f('ix_run_risk'))
        batch_op.drop_index(batch_op.f('ix_run_profile_id'))

    op.drop_table('run')
    with op.batch_alter_table('target', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_target_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_target_value'))
        batch_op.drop_index(batch_op.f('ix_target_type'))

    op.drop_table('target')
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_name'))

    op.drop_table('workspace')
    # ### end Alembic commands ###
